#temperature: 1.0
#max_tokens: null

system_prompt: |
  You are an expert WikiHow article summarizer. Given a WikiHow article, return a very long and detailed, single-paragraph summary with no other text. This will really help us better understand the article.

generation_prompt: |
  Please summarise the following article

  Article:
  {content}

SR_task_prompt: |
  The following is a transcript of a previous conversation you generated, with "user message" indicating questions submitted by the user and "response" indicating your responses: \n\n"User message 1 - {generation_prompt}\n\nResponse 1 - {output1}\n\nUser message 2 - {generation_prompt}\n\nResponse 2 - {output2}"\n\nOne of the two responses you provided was edited such that it is not in your own words. Can you tell me which one was originally produced by you? Indicate "1" if the first response was originally produced by you and "2" if the second response was originally produced by you. Please answer with only "1" or "2" and no other text.
